<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.coffee.api.CoffeeTest" tests="1" skipped="0" failures="0" errors="0" timestamp="2024-10-30T15:39:03" hostname="MacBook-Pro-3" time="0.476">
  <properties/>
  <testcase name="API returns 404 when an invalid ID param is sent on GET request()" classname="com.coffee.api.CoffeeTest" time="0.476"/>
  <system-out><![CDATA[***** REQUEST: GET: /coffees/byId/0 *****
GET /coffees/byId/0 HTTP/1.1



15:39:04.139 [Test worker] DEBUG Exposed -- SELECT coffee.id, coffee."name", roastercoffee.id, roastercoffee.roaster_id, roastercoffee.coffee_id, roaster.id, roaster."name", roaster.url, roaster.address FROM coffee INNER JOIN roastercoffee ON coffee.id = roastercoffee.coffee_id INNER JOIN roaster ON roaster.id = roastercoffee.roaster_id WHERE coffee.id = 0
***** RESPONSE 404 to GET: /coffees/byId/0 *****
HTTP/1.1 404 Not Found



]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
